
import React from 'react';
import { motion } from 'framer-motion';
import { cn } from '../lib/utils';

interface SongLyricsDisplayProps {
    html: string;
    fontSize?: number;
    onChordClick?: (chordName: string) => void;
    className?: string;
}

/**
 * Presentational Component: SongLyricsDisplay
 * 
 * Renders the HTML chord sheet generated by ChordSheetJS.
 * Enforces strict monospace font and whitespace preservation to ensure chords align
 * correctly over lyrics.
 */
const SongLyricsDisplay: React.FC<SongLyricsDisplayProps> = ({ 
    html, 
    fontSize = 16, 
    onChordClick, 
    className 
}) => {

    const handleClick = (e: React.MouseEvent<HTMLDivElement>) => {
        // Event delegation to handle clicks on dynamically generated .chord elements
        const target = e.target as HTMLElement;
        if (target.classList.contains('chord')) {
            const chordName = target.textContent?.trim();
            if (chordName && onChordClick) {
                onChordClick(chordName);
            }
        }
    };

    return (
        <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
            className={cn(
                "w-full overflow-x-auto pb-12 selection:bg-primary/30",
                className
            )}
        >
            <div 
                className="chord-sheet-container font-mono whitespace-pre-wrap"
                style={{ fontSize: `${fontSize}px`, fontFamily: "'JetBrains Mono', monospace" }}
                onClick={handleClick}
                dangerouslySetInnerHTML={{ __html: html }}
            />
            
            {!html && (
                 <div className="p-8 text-center border-2 border-dashed border-slate-200 dark:border-white/10 rounded-xl text-slate-400">
                    <p>No chord data available to render.</p>
                    <p className="text-xs mt-2 opacity-70">Try verifying the song data format.</p>
                 </div>
            )}
        </motion.div>
    );
};

export default SongLyricsDisplay;
