
import React, { memo, useCallback } from 'react';
import { motion } from 'framer-motion';
import { cn } from '../lib/utils';

/**
 * Props for the SongLyricsDisplay component.
 */
interface SongLyricsDisplayProps {
    /** The HTML string containing the formatted chord sheet. */
    html: string;
    /** The base font size for the lyrics and chords. Defaults to 16. */
    fontSize?: number;
    /** Callback function triggered when a chord name is clicked. */
    onChordClick?: (chordName: string) => void;
    /** Optional class names for styling the container. */
    className?: string;
}

/**
 * Presentational Component: SongLyricsDisplay
 * 
 * Renders the HTML chord sheet generated by ChordSheetJS.
 * Enforces strict monospace font and whitespace preservation.
 * Optimized with memoization to prevent lag on huge songs.
 *
 * @param {SongLyricsDisplayProps} props - The component props.
 * @returns {JSX.Element} The SongLyricsDisplay component.
 */
const SongLyricsDisplay: React.FC<SongLyricsDisplayProps> = ({ 
    html, 
    fontSize = 16, 
    onChordClick, 
    className 
}) => {

    const handleClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
        // Event delegation to handle clicks on dynamically generated .chord elements
        const target = e.target as HTMLElement;
        if (target.classList.contains('chord')) {
            const chordName = target.textContent?.trim();
            if (chordName && onChordClick) {
                onChordClick(chordName);
            }
        }
    }, [onChordClick]);

    return (
        <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }}
            transition={{ duration: 0.3 }}
            className={cn(
                "w-full overflow-x-auto pb-12 selection:bg-primary/30",
                className
            )}
        >
            <div 
                className="chord-sheet-container font-mono whitespace-pre-wrap"
                style={{ 
                    fontSize: `${fontSize}px`, 
                    fontFamily: "'JetBrains Mono', monospace",
                    lineHeight: '1.5' 
                }}
                onClick={handleClick}
                dangerouslySetInnerHTML={{ __html: html }}
            />
            
            {!html && (
                 <div className="p-8 text-center border-2 border-dashed border-slate-200 dark:border-white/10 rounded-xl text-slate-400">
                    <p>No chord data available to render.</p>
                    <p className="text-xs mt-2 opacity-70">Try verifying the song data format.</p>
                 </div>
            )}
        </motion.div>
    );
};

export default memo(SongLyricsDisplay);
